// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-nav/Current.tsx": () => import("../components/mockups/admin-nav/Current.tsx"),
  "./components/mockups/admin-nav/Proposed.tsx": () => import("../components/mockups/admin-nav/Proposed.tsx")
};
