#!/usr/bin/env tsx
/**
 * i18n Regression Gate
 * Run: npm run i18n:check
 *
 * Exits 0  — violation count is <= baseline (no new hardcoded strings).
 * Exits 1  — violation count EXCEEDS baseline (new hardcoded string(s) introduced).
 *
 * To update the baseline after intentional additions or after making progress:
 *   npm run i18n:report
 *
 * How the gate works:
 *   1. Scan all .tsx files in client/src using the same detection logic as i18n-audit.ts.
 *   2. Load scripts/i18n-baseline.json (committed to the repo, generated by i18n:report).
 *   3. If current total hardcoded lines > baseline total → print a diff and exit 1.
 *   4. If current total <= baseline total → print a green summary and exit 0.
 *
 * This means ALL existing hardcoded strings are "grandfathered" through the baseline.
 * Only NET NEW additions beyond the baseline cause a failure.
 */

import { readFileSync, existsSync } from "node:fs";
import { resolve, relative } from "node:path";
import fg from "fast-glob";
import { countHardcodedLines } from "./i18n-audit.ts";

// ── Paths ──────────────────────────────────────────────────────────────────
const ROOT = resolve(".");
const BASELINE_PATH = resolve("scripts/i18n-baseline.json");

// ── Baseline loading ───────────────────────────────────────────────────────
interface Baseline {
  generatedAt: string;
  totalHardcodedLines: number;
  totalTsxFiles: number;
  translatedFiles: number;
  missingEsKeys: number;
  byFile: Record<string, number>;
}

function loadBaseline(): Baseline {
  if (!existsSync(BASELINE_PATH)) {
    console.error(
      "\n  ✗ No baseline found at scripts/i18n-baseline.json\n" +
        "    Run `npm run i18n:report` first to generate it.\n",
    );
    process.exit(2);
  }
  return JSON.parse(readFileSync(BASELINE_PATH, "utf8")) as Baseline;
}

// ── Current scan ───────────────────────────────────────────────────────────
async function scanCurrent(): Promise<{ total: number; byFile: Record<string, number> }> {
  const tsxFiles = await fg("client/src/**/*.tsx", {
    cwd: ROOT,
    absolute: true,
    ignore: ["client/src/locales/**"],
  });

  const byFile: Record<string, number> = {};
  let total = 0;

  for (const filePath of tsxFiles) {
    const content = readFileSync(filePath, "utf8");
    const count = countHardcodedLines(content);
    if (count > 0) {
      const relPath = relative(ROOT, filePath);
      byFile[relPath] = count;
      total += count;
    }
  }

  return { total, byFile };
}

// ── Diff helpers ───────────────────────────────────────────────────────────
function computeDiff(
  baseline: Record<string, number>,
  current: Record<string, number>,
): { newFiles: string[]; increased: Array<{ file: string; was: number; now: number }> } {
  const newFiles: string[] = [];
  const increased: Array<{ file: string; was: number; now: number }> = [];

  for (const [file, count] of Object.entries(current)) {
    if (!(file in baseline)) {
      // Brand-new file that isn't in the baseline at all
      newFiles.push(`${file} (+${count})`);
    } else if (count > baseline[file]) {
      increased.push({ file, was: baseline[file], now: count });
    }
  }

  return { newFiles, increased };
}

// ── Main ───────────────────────────────────────────────────────────────────
async function main() {
  const baseline = loadBaseline();
  const current = await scanCurrent();

  const baselineTotal = baseline.totalHardcodedLines;
  const currentTotal = current.total;
  const delta = currentTotal - baselineTotal;

  if (delta <= 0) {
    const improvement = delta < 0 ? ` (${Math.abs(delta)} lines cleaned up since baseline 🎉)` : "";
    console.log(
      `\n  ✅ i18n gate passed — ${currentTotal} hardcoded lines` +
        ` (baseline: ${baselineTotal})${improvement}\n`,
    );
    process.exit(0);
  }

  // Failure path — show what's new
  console.error(`\n  ✗ i18n gate FAILED — ${delta} new hardcoded line(s) detected`);
  console.error(`    Current: ${currentTotal}  |  Baseline: ${baselineTotal}\n`);

  const diff = computeDiff(baseline.byFile, current.byFile);

  if (diff.newFiles.length > 0) {
    console.error("  New files with no translations:");
    for (const f of diff.newFiles) {
      console.error(`    + ${f}`);
    }
  }

  if (diff.increased.length > 0) {
    console.error("\n  Files where hardcoded count increased:");
    for (const { file, was, now } of diff.increased) {
      console.error(`    ${file}:  ${was} → ${now}  (+${now - was})`);
    }
  }

  console.error(
    "\n  Fix: wrap the new strings in t() — or, if intentional,\n" +
      "  update the baseline by running: npm run i18n:report\n",
  );

  process.exit(1);
}

main().catch((err) => {
  console.error("i18n check failed:", err);
  process.exit(1);
});
