import { pool } from "../db";

export async function runChangeOrdersMigration() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS job_change_orders (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      job_id VARCHAR(36) NOT NULL,
      customer_id VARCHAR(36),
      source_estimate_id UUID,
      co_number VARCHAR(20) NOT NULL UNIQUE,
      title TEXT NOT NULL,
      description TEXT,
      status VARCHAR(30) NOT NULL DEFAULT 'draft',
      approval_type VARCHAR(30),
      signature_data TEXT,
      approved_by_name TEXT,
      approved_at TIMESTAMP,
      subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
      tax_rate NUMERIC(5,4) DEFAULT 0,
      tax_amount NUMERIC(12,2) DEFAULT 0,
      total NUMERIC(12,2) NOT NULL DEFAULT 0,
      notes TEXT,
      internal_notes TEXT,
      photos JSONB DEFAULT '[]',
      created_by VARCHAR(36),
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS job_change_order_items (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      change_order_id UUID NOT NULL REFERENCES job_change_orders(id) ON DELETE CASCADE,
      item_type VARCHAR(30) NOT NULL DEFAULT 'labor',
      description TEXT NOT NULL,
      quantity NUMERIC(10,3) DEFAULT 1,
      unit VARCHAR(30),
      unit_price NUMERIC(12,2) DEFAULT 0,
      amount NUMERIC(12,2) DEFAULT 0,
      catalog_item_id INTEGER REFERENCES catalog_items(id),
      markup_pct NUMERIC(5,2),
      sort_order INTEGER DEFAULT 0
    )
  `);

  // NOTE: the original catalog_item_id column was mistakenly typed as UUID and
  // never pointed to a valid catalog_items row (catalog IDs have always been
  // integers). We deliberately do NOT alter that column's type in place:
  // Replit's Publish flow independently diffs dev vs prod database structure
  // (outside of this script and outside of Drizzle, which never tracked this
  // table), and any in-place uuid -> integer type change on this same-named
  // column gets re-generated by that diff as a plain ALTER COLUMN ... SET DATA
  // TYPE with no USING clause, which always fails since Postgres has no
  // automatic cast from uuid to integer. Instead we leave catalog_item_id
  // (uuid) untouched/deprecated forever, and add a brand-new integer column
  // for actual catalog linkage — a plain ADD COLUMN is always safe since there
  // is nothing to cast.
  await pool.query(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'job_change_order_items' AND column_name = 'catalog_item_id_int'
      ) THEN
        ALTER TABLE job_change_order_items ADD COLUMN catalog_item_id_int INTEGER REFERENCES catalog_items(id);
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'job_change_order_items' AND column_name = 'markup_pct'
      ) THEN
        ALTER TABLE job_change_order_items ADD COLUMN markup_pct NUMERIC(5,2);
      END IF;
    END $$;
  `);

  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_change_orders_job_id ON job_change_orders(job_id);
    CREATE INDEX IF NOT EXISTS idx_change_order_items_co_id ON job_change_order_items(change_order_id);
  `);

  // Sequence for CO numbers
  await pool.query(`
    CREATE SEQUENCE IF NOT EXISTS co_number_seq START 1
  `);

  console.log("[migration] job_change_orders + job_change_order_items tables ready");
}
